// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Qitmeer/qng/p2p/proto/v1/syncdag.proto

package qitmeer_p2p_v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncDAG struct {
	MainLocator          []*Hash     `protobuf:"bytes,1,rep,name=mainLocator,proto3" json:"mainLocator,omitempty" ssz-max:"32"`
	GraphState           *GraphState `protobuf:"bytes,2,opt,name=graphState,proto3" json:"graphState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SyncDAG) Reset()         { *m = SyncDAG{} }
func (m *SyncDAG) String() string { return proto.CompactTextString(m) }
func (*SyncDAG) ProtoMessage()    {}
func (*SyncDAG) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e0a71b5e7a5c19, []int{0}
}
func (m *SyncDAG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncDAG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncDAG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncDAG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncDAG.Merge(m, src)
}
func (m *SyncDAG) XXX_Size() int {
	return m.Size()
}
func (m *SyncDAG) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncDAG.DiscardUnknown(m)
}

var xxx_messageInfo_SyncDAG proto.InternalMessageInfo

func (m *SyncDAG) GetMainLocator() []*Hash {
	if m != nil {
		return m.MainLocator
	}
	return nil
}

func (m *SyncDAG) GetGraphState() *GraphState {
	if m != nil {
		return m.GraphState
	}
	return nil
}

type SubDAG struct {
	SyncPoint            *Hash       `protobuf:"bytes,1,opt,name=syncPoint,proto3" json:"syncPoint,omitempty"`
	GraphState           *GraphState `protobuf:"bytes,2,opt,name=graphState,proto3" json:"graphState,omitempty"`
	Blocks               []*Hash     `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty" ssz-max:"2000"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SubDAG) Reset()         { *m = SubDAG{} }
func (m *SubDAG) String() string { return proto.CompactTextString(m) }
func (*SubDAG) ProtoMessage()    {}
func (*SubDAG) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e0a71b5e7a5c19, []int{1}
}
func (m *SubDAG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubDAG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubDAG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubDAG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubDAG.Merge(m, src)
}
func (m *SubDAG) XXX_Size() int {
	return m.Size()
}
func (m *SubDAG) XXX_DiscardUnknown() {
	xxx_messageInfo_SubDAG.DiscardUnknown(m)
}

var xxx_messageInfo_SubDAG proto.InternalMessageInfo

func (m *SubDAG) GetSyncPoint() *Hash {
	if m != nil {
		return m.SyncPoint
	}
	return nil
}

func (m *SubDAG) GetGraphState() *GraphState {
	if m != nil {
		return m.GraphState
	}
	return nil
}

func (m *SubDAG) GetBlocks() []*Hash {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type ContinueSyncDAG struct {
	SyncPoint            *Hash    `protobuf:"bytes,1,opt,name=syncPoint,proto3" json:"syncPoint,omitempty"`
	Start                *Hash    `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContinueSyncDAG) Reset()         { *m = ContinueSyncDAG{} }
func (m *ContinueSyncDAG) String() string { return proto.CompactTextString(m) }
func (*ContinueSyncDAG) ProtoMessage()    {}
func (*ContinueSyncDAG) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4e0a71b5e7a5c19, []int{2}
}
func (m *ContinueSyncDAG) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContinueSyncDAG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContinueSyncDAG.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContinueSyncDAG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinueSyncDAG.Merge(m, src)
}
func (m *ContinueSyncDAG) XXX_Size() int {
	return m.Size()
}
func (m *ContinueSyncDAG) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinueSyncDAG.DiscardUnknown(m)
}

var xxx_messageInfo_ContinueSyncDAG proto.InternalMessageInfo

func (m *ContinueSyncDAG) GetSyncPoint() *Hash {
	if m != nil {
		return m.SyncPoint
	}
	return nil
}

func (m *ContinueSyncDAG) GetStart() *Hash {
	if m != nil {
		return m.Start
	}
	return nil
}

func init() {
	proto.RegisterType((*SyncDAG)(nil), "qitmeer.p2p.v1.SyncDAG")
	proto.RegisterType((*SubDAG)(nil), "qitmeer.p2p.v1.SubDAG")
	proto.RegisterType((*ContinueSyncDAG)(nil), "qitmeer.p2p.v1.ContinueSyncDAG")
}

func init() {
	proto.RegisterFile("github.com/Qitmeer/qng/v2/p2p/proto/v1/syncdag.proto", fileDescriptor_b4e0a71b5e7a5c19)
}

var fileDescriptor_b4e0a71b5e7a5c19 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x0f, 0xcc, 0x2c, 0xc9, 0x4d, 0x4d, 0x2d, 0xd2, 0x2f,
	0xcc, 0x4b, 0xd7, 0x2f, 0x30, 0x2a, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x33, 0xd4,
	0x2f, 0xae, 0xcc, 0x4b, 0x4e, 0x49, 0x4c, 0xd7, 0x03, 0x0b, 0x08, 0xf1, 0x15, 0x42, 0xd4, 0xe9,
	0x15, 0x18, 0x15, 0xe8, 0x95, 0x19, 0x4a, 0xe9, 0x11, 0x63, 0x44, 0x7a, 0x7e, 0x7a, 0x3e, 0x44,
	0xbf, 0x14, 0x51, 0x56, 0xe6, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x42, 0xb5, 0x98, 0x10, 0x65,
	0x45, 0x51, 0x62, 0x41, 0x46, 0x71, 0x49, 0x62, 0x09, 0x54, 0x97, 0x52, 0x3f, 0x23, 0x17, 0x7b,
	0x70, 0x65, 0x5e, 0xb2, 0x8b, 0xa3, 0xbb, 0x90, 0x07, 0x17, 0x77, 0x6e, 0x62, 0x66, 0x9e, 0x4f,
	0x7e, 0x72, 0x62, 0x49, 0x7e, 0x91, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xaa,
	0x57, 0xf4, 0x3c, 0x12, 0x8b, 0x33, 0x9c, 0x04, 0x3e, 0xdd, 0x93, 0xe7, 0x29, 0x2e, 0xae, 0xd2,
	0xcd, 0x4d, 0xac, 0xb0, 0x52, 0x32, 0x36, 0x52, 0x0a, 0x42, 0xd6, 0x2a, 0x64, 0xc5, 0xc5, 0x05,
	0xb6, 0x29, 0x18, 0x64, 0x93, 0x04, 0x93, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x14, 0xba, 0x41, 0xee,
	0x70, 0x15, 0x41, 0x48, 0xaa, 0x95, 0x76, 0x31, 0x72, 0xb1, 0x05, 0x97, 0x26, 0x81, 0x1c, 0x64,
	0xc4, 0xc5, 0x09, 0x0a, 0xd6, 0x80, 0xfc, 0xcc, 0xbc, 0x12, 0x09, 0x46, 0xb0, 0x29, 0x58, 0x9d,
	0x13, 0x84, 0x50, 0x46, 0x89, 0xd5, 0x42, 0x0e, 0x5c, 0x6c, 0x49, 0x39, 0xf9, 0xc9, 0xd9, 0xc5,
	0x12, 0xcc, 0x78, 0xfc, 0x2e, 0xf4, 0xe9, 0x9e, 0x3c, 0x1f, 0xdc, 0xef, 0x46, 0x06, 0x06, 0x06,
	0x4a, 0x41, 0x50, 0x7d, 0x4a, 0x85, 0x5c, 0xfc, 0xce, 0xf9, 0x79, 0x25, 0x99, 0x79, 0xa5, 0xa9,
	0xb0, 0x50, 0x25, 0xc7, 0x13, 0x5a, 0x5c, 0xac, 0xc5, 0x25, 0x89, 0x45, 0x25, 0x50, 0xf7, 0x63,
	0x57, 0x0f, 0x51, 0xe2, 0x24, 0x70, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e,
	0xc9, 0x31, 0xce, 0x78, 0x2c, 0xc7, 0x90, 0xc4, 0x06, 0x8e, 0x5a, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0x1f, 0x58, 0x4c, 0xb8, 0x02, 0x00, 0x00,
}

func (m *SyncDAG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncDAG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncDAG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.GraphState != nil {
		{
			size, err := m.GraphState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSyncdag(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MainLocator) > 0 {
		for iNdEx := len(m.MainLocator) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MainLocator[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSyncdag(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SubDAG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubDAG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubDAG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Blocks) > 0 {
		for iNdEx := len(m.Blocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Blocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSyncdag(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.GraphState != nil {
		{
			size, err := m.GraphState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSyncdag(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.SyncPoint != nil {
		{
			size, err := m.SyncPoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSyncdag(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ContinueSyncDAG) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContinueSyncDAG) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContinueSyncDAG) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Start != nil {
		{
			size, err := m.Start.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSyncdag(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.SyncPoint != nil {
		{
			size, err := m.SyncPoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSyncdag(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSyncdag(dAtA []byte, offset int, v uint64) int {
	offset -= sovSyncdag(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SyncDAG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MainLocator) > 0 {
		for _, e := range m.MainLocator {
			l = e.Size()
			n += 1 + l + sovSyncdag(uint64(l))
		}
	}
	if m.GraphState != nil {
		l = m.GraphState.Size()
		n += 1 + l + sovSyncdag(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SubDAG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SyncPoint != nil {
		l = m.SyncPoint.Size()
		n += 1 + l + sovSyncdag(uint64(l))
	}
	if m.GraphState != nil {
		l = m.GraphState.Size()
		n += 1 + l + sovSyncdag(uint64(l))
	}
	if len(m.Blocks) > 0 {
		for _, e := range m.Blocks {
			l = e.Size()
			n += 1 + l + sovSyncdag(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ContinueSyncDAG) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SyncPoint != nil {
		l = m.SyncPoint.Size()
		n += 1 + l + sovSyncdag(uint64(l))
	}
	if m.Start != nil {
		l = m.Start.Size()
		n += 1 + l + sovSyncdag(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSyncdag(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSyncdag(x uint64) (n int) {
	return sovSyncdag(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SyncDAG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncdag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncDAG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncDAG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainLocator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncdag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncdag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MainLocator = append(m.MainLocator, &Hash{})
			if err := m.MainLocator[len(m.MainLocator)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncdag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncdag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GraphState == nil {
				m.GraphState = &GraphState{}
			}
			if err := m.GraphState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyncdag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyncdag
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSyncdag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubDAG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncdag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubDAG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubDAG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncPoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncdag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncdag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SyncPoint == nil {
				m.SyncPoint = &Hash{}
			}
			if err := m.SyncPoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncdag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncdag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GraphState == nil {
				m.GraphState = &GraphState{}
			}
			if err := m.GraphState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncdag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncdag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blocks = append(m.Blocks, &Hash{})
			if err := m.Blocks[len(m.Blocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyncdag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyncdag
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSyncdag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContinueSyncDAG) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncdag
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContinueSyncDAG: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContinueSyncDAG: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncPoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncdag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncdag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SyncPoint == nil {
				m.SyncPoint = &Hash{}
			}
			if err := m.SyncPoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncdag
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncdag
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Start == nil {
				m.Start = &Hash{}
			}
			if err := m.Start.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyncdag(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyncdag
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSyncdag
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSyncdag(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSyncdag
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyncdag
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSyncdag
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSyncdag
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSyncdag
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSyncdag        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSyncdag          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSyncdag = fmt.Errorf("proto: unexpected end of group")
)
